//! ACE group-4 outer-product accumulators (`TOP*`) — INT8 family G (phase 5).
//!
//! This module hosts the tile outer-product-accumulate instructions. Phase 5 delivers
//! **family G**, the four INT8 rank-4 forms, generated by the sibling [`define_top!`] macro
//! (§3 Recommended Option B): a declarative factory modelled on the group-1 `define_dp!`
//! macro in `src/lib.rs`, but shaped for outer-product-into-tile rather than
//! dot-product-into-lane. Later phases add the BF16 rank-2 (`TOP2BF16PS`, family F, phase 6)
//! and MX-FP8 (family E, phase 7) forms by hand alongside these.
//!
//! * `TOP4BSSD` — [`_tile_top4bssd`]: signed×signed INT8 (`[i8;64]`,`[i8;64]`)
//!   (`[ace-tile-instructions.INT8_TOP.1]`).
//! * `TOP4BSUD` — [`_tile_top4bsud`]: signed×unsigned INT8 (`[i8;64]`,`[u8;64]`)
//!   (`[ace-tile-instructions.INT8_TOP.2]`).
//! * `TOP4BUSD` — [`_tile_top4busd`]: unsigned×signed INT8 (`[u8;64]`,`[i8;64]`)
//!   (`[ace-tile-instructions.INT8_TOP.3]`).
//! * `TOP4BUUD` — [`_tile_top4buud`]: unsigned×unsigned INT8 (`[u8;64]`,`[u8;64]`)
//!   (`[ace-tile-instructions.INT8_TOP.4]`).
//!
//! ==========================================================================================
//! # PINNED ACCUMULATION / ROUNDING ORDER (OQ-1 — highest-risk oracle detail)
//! ==========================================================================================
//!
//! The exact `TOP*` accumulation and rounding order is the single most correctness-sensitive
//! decision in this crate, and the differential tiebreaker (a native ACE path executed under
//! Intel SDE) is **unavailable** at this phase — SDE has no ACE emulation yet (OQ-6, layer-3
//! blocked, phase 8). The oracle here is therefore grounded directly against **ACE v1 §14**
//! (the `TOP*` tile outer-product-accumulate definition), NOT against a running reference. The
//! order below is transcribed from that rule and is the authoritative pin for every `TOP*`
//! family in this module:
//!
//! 1. **Shape.** The destination `C` is an `M×N` accumulator tile — INT32 for family G, FP32
//!    for the BF16/MX forms. Operand `A` is read row-major as `M×RANK`, operand `B` as
//!    `N×RANK` (`RANK = 4` for `TOP4*`, `2` for `TOP2*`). `M`/`N` come from the destination
//!    tile's configured `rows` / `colsb`-per-element; a group of `RANK` consecutive operand
//!    elements is one row's contraction vector (the same `a[RANK*i + k]` grouping the group-1
//!    `define_dp!` oracle uses).
//!
//! 2. **Per-element accumulate.** For every output element, in ascending `k`:
//!
//!    ```text
//!    C[m][n] := C[m][n] + Σ_{k=0..RANK-1} widen(A[m][k]) · widen(B[n][k])
//!    ```
//!
//!    The **prior** `C[m][n]` is the first term; the `RANK` products are then folded on in
//!    ascending `k` (left-to-right). For the FP32 siblings (families E/F) each fold step
//!    rounds to nearest-even (RNE) in FP32 — this left-to-right RNE order is the pinned
//!    default. For the MX-FP8 forms the per-block **BSR scale is applied to each decoded
//!    operand BEFORE the multiply** (scale-then-multiply, per block), reading the scale back
//!    through the same guard-owned BSR file the `BSR*` ops wrote it into (INV-5).
//!
//! 3. **Family G is pure integer — no rounding, no saturation.** INT8 operands widen to `i32`
//!    (signed operands **sign-extend**, unsigned operands **zero-extend** — the signedness is
//!    carried in the element type, not a runtime flag), products are formed in `i32`, and the
//!    fold uses exact two's-complement **wraparound** (`wrapping_mul` / `wrapping_add`). Group
//!    4 has **no** saturating `...DS` forms, so only the `wrap` fold exists here. Because the
//!    domain is integer, the left-to-right RNE order of step 2 does not change family G's
//!    bit-exact result, but it is pinned above for the FP32 siblings.
//!
//! Correctness grounding: **differential tiebreaker unavailable; correctness grounded against
//! ACE v1 §14.** The inline known-value pins are chosen to DISCRIMINATE this model from wrong
//! alternatives — a rank-4 widened outer product vs a naive full-array sum, and signed vs
//! unsigned INT8 widening (a `bssd` result differs from a `buud` result on a sign-sensitive
//! input).
//! ==========================================================================================
//!
//! # Dispatch
//!
//! Each form is a safe public dispatcher plus a cfg-free `_scalar` oracle (the primary path,
//! correct on every target). Family G is `ACE`-only and gates on full `ACE`
//! ([`detect::has_ace`], `[ace-tile-instructions.DETECT.1-3]`,
//! `[ace-tile-instructions.DISPATCH.1]`). No native tile shim exists yet — the `.byte`
//! native arm is layer-3-blocked until SDE gains ACE emulation (OQ-6, phase 8) — so, exactly
//! as the sibling `bsr` / `tcvtrow` families do, the dispatcher references the detector to
//! mark the gate site and takes the scalar oracle on every target.
//!
//! # OQ-8 (canonical width) surfaced here
//!
//! One canonical, largest palette-2 form per primitive: `RANK = 4` INT8 operands of `[_;64]`
//! give up to `M = N = 64/4 = 16`, i.e. a full `16×16` INT32 destination tile
//! (`rows == 16`, `colsb == 64` bytes = 16 four-byte lanes). Destinations smaller than the
//! canonical `16×16` accumulate only their configured `M×N` corner; the extra operand
//! elements are simply not read.

use crate::bsr::BsrId;
use crate::detect;
use crate::fp8::{bf16_to_fp32, fp8_e4m3_to_fp32, fp8_e5m2_to_fp32};
use crate::tile::{TileId, TileScope};

/// Palette-2 tiles cap at `rows <= 16` and `colsb <= 64`, so an INT32 accumulator tile is at
/// most `16` rows of `16` four-byte lanes. These bounds make `RANK * 16 == 64` the exact
/// operand-array length, so every `A[RANK*m + k]` / `B[RANK*n + k]` index stays in range:
/// `A` is indexed by the row `m` (so its length uses `MAX_ACC_ROWS`), `B` by the lane `n`
/// (`MAX_ACC_LANES`). The two constants are equal today; keep the pairing straight anyway so
/// a future divergence resizes the right operand.
const MAX_ACC_ROWS: usize = 16;
const MAX_ACC_LANES: usize = 16;
/// Bytes per INT32 accumulator lane.
const I32_BYTES: usize = 4;
/// Bytes per FP32 accumulator lane (family F, `TOP2BF16PS`, accumulates into FP32 tiles).
const F32_BYTES: usize = 4;
/// Contraction depth of the BF16 rank-2 outer product (`TOP2BF16PS`): two BF16 operand
/// elements per output row, so `BF16_RANK * 16 == 32` is the canonical operand-array length.
const BF16_RANK: usize = 2;
/// Contraction depth of the MX-FP8 rank-4 outer products (family E): four FP8 operand elements
/// per output row, so `MX_RANK * 16 == 64` is the canonical operand-array length. It also
/// matches [`crate::bsr::BSR_SCALE_BLOCKS`] (`== 4`), so the contraction index `k` selects the
/// per-block BSR scale directly (block `b == k`).
const MX_RANK: usize = 4;

/// Sibling of the group-1 `define_dp!` macro (`src/lib.rs`), dedicated to
/// **outer-product-into-tile** accumulation (§3 Recommended Option B). One invocation emits
/// the family-G three-name shape — a public dispatcher and its cfg-free `_scalar` oracle (the
/// `.byte` native `_hw` arm is layer-3-blocked and lands in phase 8):
///
/// * a public **dispatcher** `$name` — references the full-`ACE` detector to mark the gate
///   site (`[ace-tile-instructions.DETECT.1-3]`), then calls the oracle (the primary path on
///   every target until the native arm lands);
/// * a public **scalar oracle** `$scalar` — the portable reference and the source of truth the
///   native path will be differential-tested against, implementing the pinned ACE v1 §14
///   accumulation order (see the module header).
///
/// Named arguments (signedness is explicit, per D10 — it lives in the element TYPE, so a
/// wrong-signedness or operand-swap call is a compile error, E0308, INV-9):
/// * `name` / `scalar` — the public dispatcher and oracle identifiers (stable Rust cannot
///   concatenate identifiers without a proc-macro, which `SCOPE.4` forbids, so the pair is
///   named explicitly, exactly as `define_dp!` does).
/// * `a` / `b` — the per-element operand types (`i8` signed / `u8` unsigned); their signedness
///   threads into the widening cast (`as i32`: `i8` sign-extends, `u8` zero-extends), encoding
///   the mnemonic and making the operand types distinct so a swap does not compile.
/// * `rank` — the contraction depth (`4` for the INT8 `TOP4*` forms).
/// * `doc` — the human-readable mnemonic summary for the generated dispatcher's rustdoc.
///
/// The fold is the exact `i32` **wraparound** accumulate only — group 4 has no saturating
/// `...DS` forms, so no `saturate` arm exists here (contrast `define_dp!`).
macro_rules! define_top {
    (
        name = $name:ident,
        scalar = $scalar:ident,
        a = $a:ty,
        b = $b:ty,
        rank = $rank:expr,
        doc = $doc:expr
    ) => {
        #[doc = $doc]
        ///
        /// Rank-4 INT8 outer-product accumulate into the INT32 destination tile `dst`:
        /// `C[m][n] += Σ_k widen(a[rank*m + k]) · widen(b[rank*n + k])` with exact `i32`
        /// wraparound, in the pinned ACE v1 §14 order (see the module header). Only `dst`
        /// changes; the operand arrays are untouched.
        ///
        /// Family G is `ACE`-only and gates on full `ACE`
        /// (`[ace-tile-instructions.DETECT.1-3]`, `[ace-tile-instructions.DISPATCH.1]`); with
        /// no native shim yet (OQ-6) the detector marks the gate site and the scalar oracle
        /// runs on every target.
        pub fn $name(
            scope: &mut TileScope,
            dst: TileId,
            a: [$a; $rank * MAX_ACC_ROWS],
            b: [$b; $rank * MAX_ACC_LANES],
        ) {
            let _ = detect::has_ace; // family G gate: full ACE [DETECT.1-3]
            $scalar(scope, dst, a, b);
        }

        /// Portable outer-product-accumulate oracle — the primary, always-correct path.
        ///
        /// Widens each INT8 operand with the signedness-correct cast (`i8` sign-extends, `u8`
        /// zero-extends — the element type encodes the mnemonic), forms the rank-`$rank`
        /// products in `i32`, and folds them onto the prior `C[m][n]` with exact
        /// two's-complement wraparound (`wrapping_mul` / `wrapping_add`), per ACE v1 §14.
        /// `M`/`N` are taken from the destination tile's configured shape; the operand arrays
        /// are read but not modified.
        pub fn $scalar(
            scope: &mut TileScope,
            dst: TileId,
            a: [$a; $rank * MAX_ACC_ROWS],
            b: [$b; $rank * MAX_ACC_LANES],
        ) {
            let (rows, colsb) = scope.tile_shape(dst);
            // M = configured rows, N = four-byte INT32 lanes per row. Palette-2 bounds them to
            // <= 16 each, so RANK*index never leaves the 64-element operand arrays.
            let m_dim = (rows as usize).min(MAX_ACC_ROWS);
            let lanes = (colsb as usize / I32_BYTES).min(MAX_ACC_LANES);
            let colsb = colsb as usize;
            let bytes = scope.tile_bytes_mut(dst);
            for m in 0..m_dim {
                for n in 0..lanes {
                    let off = m * colsb + n * I32_BYTES;
                    let mut acc = i32::from_le_bytes([
                        bytes[off],
                        bytes[off + 1],
                        bytes[off + 2],
                        bytes[off + 3],
                    ]);
                    for k in 0..$rank {
                        let av = a[$rank * m + k] as i32;
                        let bv = b[$rank * n + k] as i32;
                        acc = acc.wrapping_add(av.wrapping_mul(bv));
                    }
                    bytes[off..off + I32_BYTES].copy_from_slice(&acc.to_le_bytes());
                }
            }
        }
    };
}

// ---------------------------------------------------------------------------------------------
// Family G — INT8 rank-4 outer products. Signedness is carried in the operand element type
// (D10): `[i8;64]` sign-extends, `[u8;64]` zero-extends, so `bssd`/`bsud`/`busd`/`buud` have
// DISTINCT signatures and a wrong-signedness or operand-swap call is a compile error (E0308,
// INV-9). See the module header for the pinned ACE v1 §14 accumulation order.
// [ace-tile-instructions.INT8_TOP.1] [ace-tile-instructions.INT8_TOP.2]
// [ace-tile-instructions.INT8_TOP.3] [ace-tile-instructions.INT8_TOP.4]
// [ace-tile-instructions.NAMING.1]
// ---------------------------------------------------------------------------------------------

define_top! {
    name = _tile_top4bssd,
    scalar = _tile_top4bssd_scalar,
    a = i8,
    b = i8,
    rank = 4,
    doc = "`TOP4BSSD` (`[ace-tile-instructions.INT8_TOP.1]`): signed×signed INT8 rank-4 outer-product accumulate into an INT32 tile."
}

define_top! {
    name = _tile_top4bsud,
    scalar = _tile_top4bsud_scalar,
    a = i8,
    b = u8,
    rank = 4,
    doc = "`TOP4BSUD` (`[ace-tile-instructions.INT8_TOP.2]`): signed×unsigned INT8 rank-4 outer-product accumulate into an INT32 tile. Operand order is significant (`a` signed, `b` unsigned)."
}

define_top! {
    name = _tile_top4busd,
    scalar = _tile_top4busd_scalar,
    a = u8,
    b = i8,
    rank = 4,
    doc = "`TOP4BUSD` (`[ace-tile-instructions.INT8_TOP.3]`): unsigned×signed INT8 rank-4 outer-product accumulate into an INT32 tile. Operand order is significant (`a` unsigned, `b` signed) — the inverse of `TOP4BSUD`."
}

define_top! {
    name = _tile_top4buud,
    scalar = _tile_top4buud_scalar,
    a = u8,
    b = u8,
    rank = 4,
    doc = "`TOP4BUUD` (`[ace-tile-instructions.INT8_TOP.4]`): unsigned×unsigned INT8 rank-4 outer-product accumulate into an INT32 tile."
}

/// Compile-fail demonstration of the family-G signedness typing (INV-9): the signedness lives
/// in the operand element type, so passing an operand of the wrong signedness — or swapping the
/// `SU`/`US` operands — does not type-check (rustc **E0308**), it is never a runtime error
/// value. `_tile_top4bssd` wants two signed `[i8;64]` operands; a `[u8;64]` in either slot is
/// rejected at compile time:
///
/// ```compile_fail
/// use ace::{_tile_loadconfig, _tile_top4bssd, TileConfig};
/// let cfg = TileConfig {
///     palette_id: 2,
///     rows: [16, 0, 0, 0, 0, 0, 0, 0],
///     colsb: [64, 0, 0, 0, 0, 0, 0, 0],
/// };
/// let mut scope = _tile_loadconfig(&cfg).unwrap();
/// let dst = scope.tile(0).unwrap();
/// let a = [0i8; 64]; // signed operand — correct
/// let b = [0u8; 64]; // UNSIGNED operand — wrong signedness for BSSD
/// // `_tile_top4bssd` expects `b: [i8; 64]`; `[u8; 64]` is not `[i8; 64]` (E0308):
/// _tile_top4bssd(&mut scope, dst, a, b);
/// ```
#[cfg(doctest)]
struct SignednessMismatchCompileFail;

// ---------------------------------------------------------------------------------------------
// Family F — BF16 rank-2 outer product (TOP2BF16PS, phase 6).
//
// This is the FP32 sibling of the INT8 family-G forms above: the operands are BF16 (carried as
// their raw `u16` bit patterns), the destination is an FP32 accumulator tile, and the fold uses
// the SAME pinned ACE v1 §14 accumulation order documented in the module header — the prior
// `C[m][n]` is the first term, then the `RANK = 2` products are folded on in ascending `k`
// (left-to-right), each fold step rounding to nearest-even in FP32. Unlike the MX-FP8 forms
// (family E, phase 7) there is **no block scale**: BF16 already fixes each element's magnitude.
//
// Widths are the canonical OQ-8 forms: `RANK = 2` BF16 operands of `[_;32]` give up to
// `M = N = 32/2 = 16`, a full `16×16` FP32 destination tile (`rows == 16`, `colsb == 64` bytes
// = 16 four-byte lanes). Smaller destinations accumulate only their configured `M×N` corner.
//
// Correctness grounding (per the module header): differential tiebreaker unavailable;
// correctness grounded against ACE v1 §14 (accumulation/rounding order) plus the exact BF16
// decode of `bf16_to_fp32` (a pure left shift into the FP32 high half). Family F is `ACE`-only
// and gates on full `ACE` ([ace-tile-instructions.DETECT.1-3],
// [ace-tile-instructions.DISPATCH.1]); with no native shim yet (OQ-6, phase 8) the detector
// marks the gate site and the scalar oracle runs on every target.
// [ace-tile-instructions.BF16_TOP.1] [ace-tile-instructions.NAMING.1]
// ---------------------------------------------------------------------------------------------

/// `TOP2BF16PS` (`[ace-tile-instructions.BF16_TOP.1]`): BF16 rank-2 outer-product accumulate
/// into an FP32 tile, with **no** block scale.
///
/// Decodes each BF16 operand (raw `u16` bits) to FP32 and accumulates into the FP32 destination
/// tile `dst`: `C[m][n] += Σ_k bf16→f32(a[2*m + k]) · bf16→f32(b[2*n + k])`, folded left-to-right
/// in the pinned ACE v1 §14 order (see the module header). Only `dst` changes; the operand
/// arrays are untouched.
///
/// Family F is `ACE`-only and gates on full `ACE` (`[ace-tile-instructions.DETECT.1-3]`,
/// `[ace-tile-instructions.DISPATCH.1]`); with no native shim yet (OQ-6) the detector marks the
/// gate site and the scalar oracle runs on every target.
pub fn _tile_top2bf16ps(scope: &mut TileScope, dst: TileId, a: [u16; 32], b: [u16; 32]) {
    let _ = detect::has_ace; // family F gate: full ACE [DETECT.1-3]
    _tile_top2bf16ps_scalar(scope, dst, a, b);
}

/// Portable BF16 rank-2 outer-product-accumulate oracle — the primary, always-correct path.
///
/// Decodes each BF16 operand with [`bf16_to_fp32`] (an exact left shift into the FP32 high half),
/// forms the `BF16_RANK` products in FP32, and folds them onto the prior `C[m][n]` left-to-right
/// with round-to-nearest-even at each step, per ACE v1 §14, with no block scale. `M`/`N` are
/// taken from the destination tile's configured shape; the operand arrays are read but not
/// modified.
pub fn _tile_top2bf16ps_scalar(scope: &mut TileScope, dst: TileId, a: [u16; 32], b: [u16; 32]) {
    let (rows, colsb) = scope.tile_shape(dst);
    // M = configured rows, N = four-byte FP32 lanes per row. Palette-2 bounds them to <= 16
    // each, so BF16_RANK*index never leaves the 32-element operand arrays.
    let m_dim = (rows as usize).min(MAX_ACC_ROWS);
    let lanes = (colsb as usize / F32_BYTES).min(MAX_ACC_LANES);
    let colsb = colsb as usize;
    let bytes = scope.tile_bytes_mut(dst);
    for m in 0..m_dim {
        for n in 0..lanes {
            let off = m * colsb + n * F32_BYTES;
            // Prior C[m][n] is the first term of the fold (pinned order).
            let mut acc =
                f32::from_le_bytes([bytes[off], bytes[off + 1], bytes[off + 2], bytes[off + 3]]);
            for k in 0..BF16_RANK {
                let av = bf16_to_fp32(a[BF16_RANK * m + k]);
                let bv = bf16_to_fp32(b[BF16_RANK * n + k]);
                // Left-to-right RNE fold in FP32; no block scale for BF16.
                acc += av * bv;
            }
            bytes[off..off + F32_BYTES].copy_from_slice(&acc.to_le_bytes());
        }
    }
}

// ---------------------------------------------------------------------------------------------
// Family E — MX-FP8 rank-4 outer products with a per-block BSR scale (phase 7).
//
// These are the FP32-accumulating siblings of family G, but with two extra ingredients drawn
// from the pinned ACE v1 §14 order (module header) and ACE v1 §12 (the block-scale registers):
//
//   1. **FP8 decode.** Each operand element is a raw FP8 byte, decoded to FP32 through the SAME
//      shared codecs the group-3 converts reuse (`fp8_e5m2_to_fp32` = BF8/E5M2,
//      `fp8_e4m3_to_fp32` = HF8/E4M3, `src/fp8.rs`). The four mixed-format forms pick the
//      decoder per operand: `bf8`=E5M2, `hf8`=E4M3.
//        * `TOP4MXBF8PS`  [`_tile_top4mxbf8ps`]  — BF8×BF8  (`[ace-tile-instructions.MX_TOP.1]`)
//        * `TOP4MXBHF8PS` [`_tile_top4mxbhf8ps`] — BF8×HF8  (`[ace-tile-instructions.MX_TOP.2]`)
//        * `TOP4MXHBF8PS` [`_tile_top4mxhbf8ps`] — HF8×BF8  (`[ace-tile-instructions.MX_TOP.3]`)
//        * `TOP4MXHF8PS`  [`_tile_top4mxhf8ps`]  — HF8×HF8  (`[ace-tile-instructions.MX_TOP.4]`)
//      A fifth form, `TOP4MXBSSPS` [`_tile_top4mxbssps`], is the block-scaled **signed×signed**
//      INT8 rank-4 accumulate into FP32 (`[ace-tile-instructions.MX_TOP.5]`): its operands are
//      signed `[i8;64]` (widened to FP32), so its signedness — like family G's — is carried in
//      the element type, and it is the block-scaled FP32 analogue of `TOP4BSSD`.
//
//   2. **Per-block BSR scale (INV-5, ACE v1 §12).** The `bsr: BsrId` addresses one guard-owned
//      block-scale register; the MX product reads back exactly the E8M0 exponents the family-D
//      `BSR*` ops wrote there (`[ace-tile-instructions.BSR.4-1]`) via
//      [`TileScope::bsr_reg`]. A block exponent `e` is the E8M0 shared exponent, so its scale
//      factor is `2^(e-127)` (127 = unit scale; `0xFF` is the E8M0 NaN). Per the pinned order
//      (module header, step 2) the block scale is applied to **each decoded operand BEFORE the
//      multiply** (scale-then-multiply, per block), and — since `MX_RANK == BSR_SCALE_BLOCKS ==
//      4` — the contraction index `k` selects the block directly. So each output element is:
//
//        C[m][n] += Σ_{k=0..3} (scale_k · decode_a(A[m][k])) · (scale_k · decode_b(B[n][k]))
//
//      folded left-to-right in FP32 (round-to-nearest-even), the prior `C[m][n]` first. Because
//      the scale is applied before the multiply and per block, a scaled product differs from an
//      unscaled one, and applying the scale before the multiply differs from scaling the
//      accumulated sum afterwards — both pinned by the inline known-value tests.
//
// Correctness grounding (per the module header): **differential tiebreaker unavailable;
// correctness grounded against ACE v1 §14 (accumulation + block-scale application order) and
// §12 (BSR scale).** Family E is `ACE`-only and gates on full `ACE`
// ([ace-tile-instructions.DETECT.1-3], [ace-tile-instructions.DISPATCH.1]); with no native shim
// yet (OQ-6, phase 8) the detector marks the gate site and the scalar oracle runs on every
// target. Widths are the canonical OQ-8 forms: `MX_RANK = 4` FP8 operands of `[_;64]` give up
// to a full `16×16` FP32 destination tile; smaller destinations accumulate only their `M×N`
// corner. [ace-tile-instructions.MX_TOP.1..5] [ace-tile-instructions.BSR.4-1]
// [ace-tile-instructions.NAMING.1]
// ---------------------------------------------------------------------------------------------

/// The E8M0 block-scale factor of one BSR exponent (ACE v1 §12): `2^(exp-127)`, so `127` is unit
/// scale. `0xFF` is the E8M0 NaN encoding. This is the per-block factor the MX-FP8 products apply
/// to each decoded operand before the multiply (pinned order, module header).
fn mx_block_scale(exp: u8) -> f32 {
    if exp == 0xFF {
        f32::NAN
    } else {
        2f32.powi(exp as i32 - 127)
    }
}

/// Shared MX rank-4 outer-product-accumulate kernel over the pinned ACE v1 §14 order. Reads the
/// per-block E8M0 scale back from the guard-owned BSR file (INV-5), decodes each operand element
/// with the caller-supplied per-operand decoder, applies the block scale to each decoded operand
/// before the multiply, and folds the `MX_RANK` products onto the prior `C[m][n]` left-to-right
/// in FP32. `M`/`N` come from the destination tile's configured shape; the operands are read but
/// not modified.
///
/// NOTE (pending rev-1.15 PDF confirmation): ONE shared BSR scale is applied to BOTH operands,
/// so each product carries `s_k²` — the pinned transcription of §14/§12. Conventional OCP MX
/// gives each operand tile its own block scale (`s_a·s_b` per product); if the PDF names a
/// second BSR operand, this kernel (and the single-`bsr` public signatures) must grow one.
fn mx_accumulate<T: Copy>(
    scope: &mut TileScope,
    dst: TileId,
    a: [T; MX_RANK * MAX_ACC_ROWS],
    b: [T; MX_RANK * MAX_ACC_LANES],
    bsr: BsrId,
    decode_a: impl Fn(T) -> f32,
    decode_b: impl Fn(T) -> f32,
) {
    // Read the block scale back through the shared model FIRST (INV-5), ending the immutable
    // borrow before the mutable tile-byte borrow below. The scales are the exact E8M0 exponents
    // the family-D BSR* ops wrote into this register.
    let scales = *scope.bsr_reg(bsr).scales();
    let block_scale: [f32; MX_RANK] = core::array::from_fn(|k| mx_block_scale(scales[k]));

    let (rows, colsb) = scope.tile_shape(dst);
    let m_dim = (rows as usize).min(MAX_ACC_ROWS);
    let lanes = (colsb as usize / F32_BYTES).min(MAX_ACC_LANES);
    let colsb = colsb as usize;
    let bytes = scope.tile_bytes_mut(dst);
    for m in 0..m_dim {
        for n in 0..lanes {
            let off = m * colsb + n * F32_BYTES;
            // Prior C[m][n] is the first term of the fold (pinned order).
            let mut acc =
                f32::from_le_bytes([bytes[off], bytes[off + 1], bytes[off + 2], bytes[off + 3]]);
            for k in 0..MX_RANK {
                // Block b == k (MX_RANK == BSR_SCALE_BLOCKS). Scale applied to EACH decoded
                // operand before the multiply (scale-then-multiply, per block).
                let s = block_scale[k];
                let av = decode_a(a[MX_RANK * m + k]) * s;
                let bv = decode_b(b[MX_RANK * n + k]) * s;
                acc += av * bv;
            }
            bytes[off..off + F32_BYTES].copy_from_slice(&acc.to_le_bytes());
        }
    }
}

/// `TOP4MXBF8PS` (`[ace-tile-instructions.MX_TOP.1]`): BF8×BF8 (both E5M2) rank-4 outer-product
/// accumulate into an FP32 tile, with the per-block BSR scale applied (INV-5).
///
/// `C[m][n] += Σ_k (s_k·bf8→f32(a[4m+k]))·(s_k·bf8→f32(b[4n+k]))`, folded left-to-right in the
/// pinned ACE v1 §14 order, `s_k = 2^(e_k-127)` read from `bsr` (§12). Only `dst` changes.
///
/// Family E is `ACE`-only and gates on full `ACE` (`[ace-tile-instructions.DETECT.1-3]`,
/// `[ace-tile-instructions.DISPATCH.1]`); with no native shim yet (OQ-6) the detector marks the
/// gate site and the scalar oracle runs on every target.
pub fn _tile_top4mxbf8ps(scope: &mut TileScope, dst: TileId, a: [u8; 64], b: [u8; 64], bsr: BsrId) {
    let _ = detect::has_ace; // family E gate: full ACE [DETECT.1-3]
    _tile_top4mxbf8ps_scalar(scope, dst, a, b, bsr);
}

/// Portable `TOP4MXBF8PS` oracle — the primary, always-correct path. Decodes both operands as
/// BF8 (E5M2) and accumulates per the pinned order with the per-block BSR scale.
pub fn _tile_top4mxbf8ps_scalar(
    scope: &mut TileScope,
    dst: TileId,
    a: [u8; 64],
    b: [u8; 64],
    bsr: BsrId,
) {
    mx_accumulate(scope, dst, a, b, bsr, fp8_e5m2_to_fp32, fp8_e5m2_to_fp32);
}

/// `TOP4MXBHF8PS` (`[ace-tile-instructions.MX_TOP.2]`): BF8×HF8 rank-4 outer-product accumulate
/// into an FP32 tile (operand `a` E5M2, operand `b` E4M3), with the per-block BSR scale applied.
///
/// WARNING — operand order is significant and the type system cannot catch a swap here: both
/// operands are raw FP8 bytes (`[u8; 64]`, mirroring the eventual intrinsic signature, D5), so
/// transposing `a` and `b` silently decodes each operand with the other's format. This is the
/// inverse of [`_tile_top4mxhbf8ps`]; double-check the call site against the mnemonic (B = BF8
/// first, H = HF8 second). Gates as [`_tile_top4mxbf8ps`].
pub fn _tile_top4mxbhf8ps(
    scope: &mut TileScope,
    dst: TileId,
    a: [u8; 64],
    b: [u8; 64],
    bsr: BsrId,
) {
    let _ = detect::has_ace; // family E gate: full ACE [DETECT.1-3]
    _tile_top4mxbhf8ps_scalar(scope, dst, a, b, bsr);
}

/// Portable `TOP4MXBHF8PS` oracle — operand `a` decoded as BF8 (E5M2), operand `b` as HF8
/// (E4M3), accumulated per the pinned order with the per-block BSR scale.
pub fn _tile_top4mxbhf8ps_scalar(
    scope: &mut TileScope,
    dst: TileId,
    a: [u8; 64],
    b: [u8; 64],
    bsr: BsrId,
) {
    mx_accumulate(scope, dst, a, b, bsr, fp8_e5m2_to_fp32, fp8_e4m3_to_fp32);
}

/// `TOP4MXHBF8PS` (`[ace-tile-instructions.MX_TOP.3]`): HF8×BF8 rank-4 outer-product accumulate
/// into an FP32 tile (operand `a` E4M3, operand `b` E5M2), with the per-block BSR scale applied.
///
/// WARNING — operand order is significant and the type system cannot catch a swap here: both
/// operands are raw FP8 bytes (`[u8; 64]`, mirroring the eventual intrinsic signature, D5), so
/// transposing `a` and `b` silently decodes each operand with the other's format. This is the
/// inverse of [`_tile_top4mxbhf8ps`]; double-check the call site against the mnemonic (H = HF8
/// first, B = BF8 second). Gates as [`_tile_top4mxbf8ps`].
pub fn _tile_top4mxhbf8ps(
    scope: &mut TileScope,
    dst: TileId,
    a: [u8; 64],
    b: [u8; 64],
    bsr: BsrId,
) {
    let _ = detect::has_ace; // family E gate: full ACE [DETECT.1-3]
    _tile_top4mxhbf8ps_scalar(scope, dst, a, b, bsr);
}

/// Portable `TOP4MXHBF8PS` oracle — operand `a` decoded as HF8 (E4M3), operand `b` as BF8
/// (E5M2), accumulated per the pinned order with the per-block BSR scale.
pub fn _tile_top4mxhbf8ps_scalar(
    scope: &mut TileScope,
    dst: TileId,
    a: [u8; 64],
    b: [u8; 64],
    bsr: BsrId,
) {
    mx_accumulate(scope, dst, a, b, bsr, fp8_e4m3_to_fp32, fp8_e5m2_to_fp32);
}

/// `TOP4MXHF8PS` (`[ace-tile-instructions.MX_TOP.4]`): HF8×HF8 (both E4M3) rank-4 outer-product
/// accumulate into an FP32 tile, with the per-block BSR scale applied (INV-5). Gates as
/// [`_tile_top4mxbf8ps`].
pub fn _tile_top4mxhf8ps(scope: &mut TileScope, dst: TileId, a: [u8; 64], b: [u8; 64], bsr: BsrId) {
    let _ = detect::has_ace; // family E gate: full ACE [DETECT.1-3]
    _tile_top4mxhf8ps_scalar(scope, dst, a, b, bsr);
}

/// Portable `TOP4MXHF8PS` oracle — decodes both operands as HF8 (E4M3) and accumulates per the
/// pinned order with the per-block BSR scale.
pub fn _tile_top4mxhf8ps_scalar(
    scope: &mut TileScope,
    dst: TileId,
    a: [u8; 64],
    b: [u8; 64],
    bsr: BsrId,
) {
    mx_accumulate(scope, dst, a, b, bsr, fp8_e4m3_to_fp32, fp8_e4m3_to_fp32);
}

/// `TOP4MXBSSPS` (`[ace-tile-instructions.MX_TOP.5]`): block-scaled **signed×signed** INT8
/// rank-4 outer-product accumulate into an FP32 tile, with the per-block BSR scale applied
/// (INV-5). Both operands are signed `[i8;64]` (widened to FP32), so the signedness — as in
/// family G — lives in the element type; it is the block-scaled FP32 analogue of `TOP4BSSD`.
/// Gates as [`_tile_top4mxbf8ps`].
pub fn _tile_top4mxbssps(scope: &mut TileScope, dst: TileId, a: [i8; 64], b: [i8; 64], bsr: BsrId) {
    let _ = detect::has_ace; // family E gate: full ACE [DETECT.1-3]
    _tile_top4mxbssps_scalar(scope, dst, a, b, bsr);
}

/// Portable `TOP4MXBSSPS` oracle — widens both signed INT8 operands to FP32 and accumulates per
/// the pinned order with the per-block BSR scale.
pub fn _tile_top4mxbssps_scalar(
    scope: &mut TileScope,
    dst: TileId,
    a: [i8; 64],
    b: [i8; 64],
    bsr: BsrId,
) {
    mx_accumulate(scope, dst, a, b, bsr, |x| x as f32, |x| x as f32);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tile::{_tile_loadconfig, _tile_zero, TileConfig};

    /// A live palette-2 guard with tile 0 configured as an `m_rows × n_lanes` INT32
    /// accumulator (`colsb = n_lanes * 4` bytes). Every INT8 `TOP4*` writes into this tile.
    fn int32_scope(m_rows: u8, n_lanes: u16) -> TileScope {
        let cfg = TileConfig {
            palette_id: 2,
            rows: [m_rows, 0, 0, 0, 0, 0, 0, 0],
            colsb: [n_lanes * 4, 0, 0, 0, 0, 0, 0, 0],
        };
        _tile_loadconfig(&cfg).unwrap()
    }

    /// Read the whole INT32 destination tile back as an `M×N` matrix of `i32` lanes, through
    /// the guard's register-model byte accessor.
    fn read_matrix(scope: &TileScope, dst: TileId) -> Vec<Vec<i32>> {
        let (rows, colsb) = scope.tile_shape(dst);
        let lanes = colsb as usize / I32_BYTES;
        let bytes = scope.tile_bytes_ref(dst);
        (0..rows as usize)
            .map(|m| {
                (0..lanes)
                    .map(|n| {
                        let off = m * colsb as usize + n * I32_BYTES;
                        i32::from_le_bytes([
                            bytes[off],
                            bytes[off + 1],
                            bytes[off + 2],
                            bytes[off + 3],
                        ])
                    })
                    .collect()
            })
            .collect()
    }

    /// Run `_tile_top4bssd` once on a freshly zeroed `m×n` tile and return the result matrix —
    /// i.e. the plain rank-4 outer product with no prior accumulation.
    fn bssd_product(m_rows: u8, n_lanes: u16, a: [i8; 64], b: [i8; 64]) -> Vec<Vec<i32>> {
        let mut scope = int32_scope(m_rows, n_lanes);
        let dst = scope.tile(0).unwrap();
        _tile_top4bssd(&mut scope, dst, a, b);
        read_matrix(&scope, dst)
    }

    /// Independent reference: the rank-4 widened outer product with explicit signedness.
    fn reference(m_rows: usize, n_lanes: usize, a: &[i32; 64], b: &[i32; 64]) -> Vec<Vec<i32>> {
        (0..m_rows)
            .map(|m| {
                (0..n_lanes)
                    .map(|n| {
                        let mut acc = 0i32;
                        for k in 0..4 {
                            acc = acc.wrapping_add(a[4 * m + k].wrapping_mul(b[4 * n + k]));
                        }
                        acc
                    })
                    .collect()
            })
            .collect()
    }

    /// All four INT8 signedness forms are oracle-correct with exact `i32` wraparound, and the
    /// sources are left untouched (`[ace-tile-instructions.INT8_TOP.1..4]`). The chosen input
    /// carries a sign bit in both operands so the four results are pairwise DISTINCT — a
    /// signed-vs-unsigned widening bug would collapse them.
    /// `top::int8_bssd_bsud_busd_buud_oracle`
    #[test]
    fn int8_bssd_bsud_busd_buud_oracle() {
        // A 2x2 tile: M=2 rows of A, N=2 rows of B (each a 4-vector). High-bit elements make
        // signed and unsigned widenings diverge.
        // Both operands' first RANK elements (feeding C[0][0]) carry a sign bit, so all four
        // widenings diverge there — b[0..4] = -40,-33,-26,-19 and a[0..4] = -30,-25,-20,-15.
        let ai8: [i8; 64] = core::array::from_fn(|i| (i as i8).wrapping_mul(5).wrapping_sub(30));
        let bi8: [i8; 64] = core::array::from_fn(|i| (i as i8).wrapping_mul(7).wrapping_sub(40));
        let au8: [u8; 64] = core::array::from_fn(|i| ai8[i] as u8);
        let bu8: [u8; 64] = core::array::from_fn(|i| bi8[i] as u8);

        let mut scope = int32_scope(2, 2);
        let dst = scope.tile(0).unwrap();

        // bssd: both signed.
        _tile_top4bssd(&mut scope, dst, ai8, bi8);
        let got_ss = read_matrix(&scope, dst);
        let a_s: [i32; 64] = core::array::from_fn(|i| ai8[i] as i32);
        let b_s: [i32; 64] = core::array::from_fn(|i| bi8[i] as i32);
        let a_u: [i32; 64] = core::array::from_fn(|i| au8[i] as i32);
        let b_u: [i32; 64] = core::array::from_fn(|i| bu8[i] as i32);
        assert_eq!(got_ss, reference(2, 2, &a_s, &b_s), "bssd = signed×signed");

        // Sources untouched: re-run into a fresh tile with the same arrays and check they
        // still produce the same result (the op consumes arrays by value, so this also pins
        // that the public API does not require mutable operands).
        _tile_zero(&mut scope, dst);
        _tile_top4bsud(&mut scope, dst, ai8, bu8);
        assert_eq!(
            read_matrix(&scope, dst),
            reference(2, 2, &a_s, &b_u),
            "bsud = signed×unsigned"
        );

        _tile_zero(&mut scope, dst);
        _tile_top4busd(&mut scope, dst, au8, bi8);
        assert_eq!(
            read_matrix(&scope, dst),
            reference(2, 2, &a_u, &b_s),
            "busd = unsigned×signed"
        );

        _tile_zero(&mut scope, dst);
        _tile_top4buud(&mut scope, dst, au8, bu8);
        assert_eq!(
            read_matrix(&scope, dst),
            reference(2, 2, &a_u, &b_u),
            "buud = unsigned×unsigned"
        );

        // Discriminating: with sign bits set, the four widenings give pairwise-distinct C[0][0]
        // (a signed-vs-unsigned bug that treated all operands the same would make these equal).
        let c_ss = reference(2, 2, &a_s, &b_s)[0][0];
        let c_su = reference(2, 2, &a_s, &b_u)[0][0];
        let c_us = reference(2, 2, &a_u, &b_s)[0][0];
        let c_uu = reference(2, 2, &a_u, &b_u)[0][0];
        assert!(
            c_ss != c_su && c_ss != c_us && c_ss != c_uu && c_su != c_uu && c_us != c_uu,
            "sign-sensitive input must make the four forms distinct: ss={c_ss} su={c_su} us={c_us} uu={c_uu}"
        );
    }

    /// INT8 signedness-matrix relations. When an operand's bytes are all in `[0, 127]`, its
    /// signed and unsigned widenings coincide, so specific pairs of the four forms MUST be
    /// bit-for-bit equal; and when a byte has its high bit set the forms MUST differ. These
    /// crisp equalities/inequalities pin the signed-vs-unsigned widening.
    /// `top::int8_signedness_matrix_relations`
    #[test]
    fn int8_signedness_matrix_relations() {
        // b is entirely non-negative (< 128), so unsigned(b) == signed(b): the b-signedness
        // axis is a no-op and bssd==bsud, busd==buud. a carries sign bits, so the a-signedness
        // axis still separates {bssd,bsud} from {busd,buud}.
        let a_hi: [i8; 64] = core::array::from_fn(|i| (i as i8).wrapping_mul(9).wrapping_sub(64));
        let b_nonneg_i: [i8; 64] = core::array::from_fn(|i| (i as u8 % 100) as i8); // 0..99
        let b_nonneg_u: [u8; 64] = core::array::from_fn(|i| b_nonneg_i[i] as u8);
        let a_hi_u: [u8; 64] = core::array::from_fn(|i| a_hi[i] as u8);

        let ss = bssd_matrix(&a_hi, &b_nonneg_i);
        let su = bsud_matrix(&a_hi, &b_nonneg_u);
        let us = busd_matrix(&a_hi_u, &b_nonneg_i);
        let uu = buud_matrix(&a_hi_u, &b_nonneg_u);
        assert_eq!(
            ss, su,
            "b non-negative => b-signedness is a no-op: bssd == bsud"
        );
        assert_eq!(
            us, uu,
            "b non-negative => b-signedness is a no-op: busd == buud"
        );
        assert_ne!(
            ss, us,
            "a carries sign bits => a-signedness separates: bssd != busd"
        );

        // Symmetric: a entirely non-negative, b carries sign bits => a-signedness is a no-op
        // (bssd==busd, bsud==buud) and b-signedness separates (bssd != bsud).
        let a_nonneg_i: [i8; 64] = core::array::from_fn(|i| (i as u8 % 100) as i8);
        let a_nonneg_u: [u8; 64] = core::array::from_fn(|i| a_nonneg_i[i] as u8);
        let b_hi_i: [i8; 64] =
            core::array::from_fn(|i| (i as i8).wrapping_mul(11).wrapping_sub(70));
        let b_hi_u: [u8; 64] = core::array::from_fn(|i| b_hi_i[i] as u8);

        let ss2 = bssd_matrix(&a_nonneg_i, &b_hi_i);
        let su2 = bsud_matrix(&a_nonneg_i, &b_hi_u);
        let us2 = busd_matrix(&a_nonneg_u, &b_hi_i);
        let uu2 = buud_matrix(&a_nonneg_u, &b_hi_u);
        assert_eq!(
            ss2, us2,
            "a non-negative => a-signedness is a no-op: bssd == busd"
        );
        assert_eq!(
            su2, uu2,
            "a non-negative => a-signedness is a no-op: bsud == buud"
        );
        assert_ne!(
            ss2, su2,
            "b carries sign bits => b-signedness separates: bssd != bsud"
        );
    }

    // Small per-form helpers that run one product on a fresh 2x2 tile and return the matrix.
    fn bssd_matrix(a: &[i8; 64], b: &[i8; 64]) -> Vec<Vec<i32>> {
        let mut s = int32_scope(2, 2);
        let d = s.tile(0).unwrap();
        _tile_top4bssd(&mut s, d, *a, *b);
        read_matrix(&s, d)
    }
    fn bsud_matrix(a: &[i8; 64], b: &[u8; 64]) -> Vec<Vec<i32>> {
        let mut s = int32_scope(2, 2);
        let d = s.tile(0).unwrap();
        _tile_top4bsud(&mut s, d, *a, *b);
        read_matrix(&s, d)
    }
    fn busd_matrix(a: &[u8; 64], b: &[i8; 64]) -> Vec<Vec<i32>> {
        let mut s = int32_scope(2, 2);
        let d = s.tile(0).unwrap();
        _tile_top4busd(&mut s, d, *a, *b);
        read_matrix(&s, d)
    }
    fn buud_matrix(a: &[u8; 64], b: &[u8; 64]) -> Vec<Vec<i32>> {
        let mut s = int32_scope(2, 2);
        let d = s.tile(0).unwrap();
        _tile_top4buud(&mut s, d, *a, *b);
        read_matrix(&s, d)
    }

    /// Outer-product bilinearity (`[ace-tile-instructions.TESTING.3]`): on a zeroed tile the
    /// product is linear in each operand. Additive in `a`: `P(a1+a2, b) == P(a1,b) + P(a2,b)`;
    /// additive in `b`: `P(a, b1+b2) == P(a,b1) + P(a,b2)` (elementwise, in the `i32` ring). Small
    /// operands keep the `i8` sums in range so `a1+a2` is a valid signed byte.
    /// `top::outer_product_bilinearity`
    #[test]
    fn outer_product_bilinearity() {
        let a1: [i8; 64] = core::array::from_fn(|i| (i as i8 % 7) - 3);
        let a2: [i8; 64] = core::array::from_fn(|i| (i as i8 % 5) - 2);
        let b1: [i8; 64] = core::array::from_fn(|i| (i as i8 % 6) - 3);
        let b2: [i8; 64] = core::array::from_fn(|i| (i as i8 % 4) - 1);
        let asum: [i8; 64] = core::array::from_fn(|i| a1[i] + a2[i]);
        let bsum: [i8; 64] = core::array::from_fn(|i| b1[i] + b2[i]);

        let add = |x: &[Vec<i32>], y: &[Vec<i32>]| -> Vec<Vec<i32>> {
            x.iter()
                .zip(y)
                .map(|(rx, ry)| {
                    rx.iter()
                        .zip(ry)
                        .map(|(&a, &b)| a.wrapping_add(b))
                        .collect()
                })
                .collect()
        };

        // Additive in a.
        let lhs_a = bssd_product(4, 4, asum, b1);
        let rhs_a = add(&bssd_product(4, 4, a1, b1), &bssd_product(4, 4, a2, b1));
        assert_eq!(lhs_a, rhs_a, "P(a1+a2, b) == P(a1,b) + P(a2,b)");

        // Additive in b.
        let lhs_b = bssd_product(4, 4, a1, bsum);
        let rhs_b = add(&bssd_product(4, 4, a1, b1), &bssd_product(4, 4, a1, b2));
        assert_eq!(lhs_b, rhs_b, "P(a, b1+b2) == P(a,b1) + P(a,b2)");
    }

    /// TILEZERO-then-accumulate equals a plain product (INV-4,
    /// `[ace-tile-instructions.TESTING.3]`): on a zeroed tile a single `TOP` writes exactly the
    /// outer product `P`; accumulating a second time writes `2P`; and seeding the tile then
    /// running once writes `C_prev + P`. Also confirms `_tile_zero` resets the accumulator.
    /// `top::tilezero_then_accumulate_equals_plain_product`
    #[test]
    fn tilezero_then_accumulate_equals_plain_product() {
        let a: [i8; 64] = core::array::from_fn(|i| (i as i8 % 9) - 4);
        let b: [i8; 64] = core::array::from_fn(|i| (i as i8 % 8) - 3);
        let a_s: [i32; 64] = core::array::from_fn(|i| a[i] as i32);
        let b_s: [i32; 64] = core::array::from_fn(|i| b[i] as i32);
        let p = reference(3, 3, &a_s, &b_s);
        let twice: Vec<Vec<i32>> = p
            .iter()
            .map(|row| row.iter().map(|&v| v.wrapping_add(v)).collect())
            .collect();

        let mut scope = int32_scope(3, 3);
        let dst = scope.tile(0).unwrap();

        // Zeroed tile + one product == plain product P.
        _tile_top4bssd(&mut scope, dst, a, b);
        assert_eq!(read_matrix(&scope, dst), p, "zeroed + one product == P");

        // Accumulate again == 2P (not idempotent).
        _tile_top4bssd(&mut scope, dst, a, b);
        assert_eq!(read_matrix(&scope, dst), twice, "second accumulate == 2P");

        // TILEZERO resets, then one product == P again.
        _tile_zero(&mut scope, dst);
        _tile_top4bssd(&mut scope, dst, a, b);
        assert_eq!(
            read_matrix(&scope, dst),
            p,
            "TILEZERO then one product == P"
        );
    }

    /// Hand-computed known-value pins (`[ace-tile-instructions.TESTING.4]`), independent of the
    /// implementation. These DISCRIMINATE the implemented model from two wrong alternatives:
    /// (1) a rank-4 widened OUTER product (C[m][n] = dot of A-row m and B-row n) vs a naive
    /// full-array sum; (2) signed vs unsigned INT8 widening.
    /// `top::int8_known_value_pins`
    #[test]
    fn int8_known_value_pins() {
        // 2x2 tile. A rows: [1,2,3,4] and [5,6,7,8]; B rows: [2,0,0,0] and [0,0,0,3].
        let mut a = [0i8; 64];
        let mut b = [0i8; 64];
        a[0..4].copy_from_slice(&[1, 2, 3, 4]);
        a[4..8].copy_from_slice(&[5, 6, 7, 8]);
        b[0..4].copy_from_slice(&[2, 0, 0, 0]);
        b[4..8].copy_from_slice(&[0, 0, 0, 3]);

        // Outer product:
        //   C[0][0] = 1*2 + 2*0 + 3*0 + 4*0 = 2
        //   C[0][1] = 1*0 + 2*0 + 3*0 + 4*3 = 12
        //   C[1][0] = 5*2 + 0 + 0 + 0       = 10
        //   C[1][1] = 0 + 0 + 0 + 8*3       = 24
        // A naive full-array sum (Σ a[i]*b[i] over all 64) would give a SINGLE scalar 2, not
        // this 2x2 matrix — the pin discriminates the outer-product structure.
        let got = bssd_product(2, 2, a, b);
        assert_eq!(
            got,
            vec![vec![2, 12], vec![10, 24]],
            "rank-4 outer product pins"
        );

        // Signed vs unsigned widening: a[0] = -1 (0xFF). With b[0]=2 in B-row 0, C[0][0] for
        // BSSD is (-1)*2 = -2; for BUUD (a widened as u8 = 255) it is 255*2 = 510. A single
        // discriminating byte, so bssd and buud MUST differ here.
        let mut sa = [0i8; 64];
        let mut sb = [0i8; 64];
        sa[0] = -1; // 0xFF
        sb[0] = 2;
        let ua: [u8; 64] = core::array::from_fn(|i| sa[i] as u8);
        let ub: [u8; 64] = core::array::from_fn(|i| sb[i] as u8);
        assert_eq!(
            bssd_matrix(&sa, &sb)[0][0],
            -2,
            "BSSD widens a[0]=0xFF as signed -1"
        );
        assert_eq!(
            buud_matrix(&ua, &ub)[0][0],
            510,
            "BUUD widens a[0]=0xFF as unsigned 255"
        );
    }

    /// System-as-a-whole wiring check: the full family-G accumulate end to end, printing
    /// observable INT32-tile state — a `TOP4BSSD` accumulate mutates `dst` as `C_prev + rank-4
    /// product`, and `TILEZERO` then one product equals the plain product. Also prints the
    /// gate helper family G reads.
    #[test]
    fn end_to_end_top4_accumulate() {
        let a: [i8; 64] = core::array::from_fn(|i| (i as i8 % 5) - 2);
        let b: [i8; 64] = core::array::from_fn(|i| (i as i8 % 4) - 1);
        let a_s: [i32; 64] = core::array::from_fn(|i| a[i] as i32);
        let b_s: [i32; 64] = core::array::from_fn(|i| b[i] as i32);
        let product = reference(2, 2, &a_s, &b_s);

        let mut scope = int32_scope(2, 2);
        let dst = scope.tile(0).unwrap();

        // Seed a known nonzero C_prev via one product, snapshot it.
        _tile_top4bssd(&mut scope, dst, a, b);
        let c_prev = read_matrix(&scope, dst);
        println!("E2E c_prev = {c_prev:?}");

        // Accumulate again: dst must be C_prev + product, elementwise.
        _tile_top4bssd(&mut scope, dst, a, b);
        let c_after = read_matrix(&scope, dst);
        println!("E2E c_after (C_prev + product) = {c_after:?}");
        let expected: Vec<Vec<i32>> = c_prev
            .iter()
            .zip(&product)
            .map(|(pr, pp)| {
                pr.iter()
                    .zip(pp)
                    .map(|(&x, &y)| x.wrapping_add(y))
                    .collect()
            })
            .collect();
        assert_eq!(
            c_after, expected,
            "accumulate mutates dst as C_prev + rank-4 product"
        );

        // TILEZERO then one product == plain product.
        _tile_zero(&mut scope, dst);
        _tile_top4bssd(&mut scope, dst, a, b);
        let c_zeroed = read_matrix(&scope, dst);
        println!("E2E tilezero-then-one-product = {c_zeroed:?}; plain product = {product:?}");
        assert_eq!(
            c_zeroed, product,
            "TILEZERO then one product == plain product"
        );

        println!("E2E detect has_ace={}", crate::detect::has_ace());
    }

    // -----------------------------------------------------------------------------------------
    // Family F — BF16 rank-2 outer product (TOP2BF16PS) tests.
    // -----------------------------------------------------------------------------------------

    use crate::fp8::fp32_to_bf16_rne;

    /// A live palette-2 guard with tile 0 configured as an `m_rows × n_lanes` FP32 accumulator
    /// (`colsb = n_lanes * 4` bytes). Every BF16 `TOP2*` writes into this tile.
    fn fp32_scope(m_rows: u8, n_lanes: u16) -> TileScope {
        let cfg = TileConfig {
            palette_id: 2,
            rows: [m_rows, 0, 0, 0, 0, 0, 0, 0],
            colsb: [n_lanes * 4, 0, 0, 0, 0, 0, 0, 0],
        };
        _tile_loadconfig(&cfg).unwrap()
    }

    /// Read the whole FP32 destination tile back as an `M×N` matrix of `f32` lanes, through the
    /// guard's register-model byte accessor.
    fn read_matrix_f32(scope: &TileScope, dst: TileId) -> Vec<Vec<f32>> {
        let (rows, colsb) = scope.tile_shape(dst);
        let lanes = colsb as usize / F32_BYTES;
        let bytes = scope.tile_bytes_ref(dst);
        (0..rows as usize)
            .map(|m| {
                (0..lanes)
                    .map(|n| {
                        let off = m * colsb as usize + n * F32_BYTES;
                        f32::from_le_bytes([
                            bytes[off],
                            bytes[off + 1],
                            bytes[off + 2],
                            bytes[off + 3],
                        ])
                    })
                    .collect()
            })
            .collect()
    }

    /// Encode an array of FP32 values to their BF16 bit patterns (the operand form). Every value
    /// used in these tests is chosen exactly representable in BF16, so this round-trips exactly.
    fn to_bf16(vals: &[f32; 32]) -> [u16; 32] {
        core::array::from_fn(|i| fp32_to_bf16_rne(vals[i]))
    }

    /// Run `_tile_top2bf16ps` once on a freshly zeroed `m×n` tile and return the result matrix —
    /// i.e. the plain rank-2 BF16 outer product with no prior accumulation.
    fn bf16_product(m_rows: u8, n_lanes: u16, a: [u16; 32], b: [u16; 32]) -> Vec<Vec<f32>> {
        let mut scope = fp32_scope(m_rows, n_lanes);
        let dst = scope.tile(0).unwrap();
        _tile_top2bf16ps(&mut scope, dst, a, b);
        read_matrix_f32(&scope, dst)
    }

    /// Independent FP32 reference: the rank-2 outer product folded left-to-right, decoding the
    /// operands from the same BF16 arrays the op sees (so the reference and oracle share the
    /// decode but not the accumulation code).
    fn reference_bf16(
        m_rows: usize,
        n_lanes: usize,
        a: &[u16; 32],
        b: &[u16; 32],
    ) -> Vec<Vec<f32>> {
        (0..m_rows)
            .map(|m| {
                (0..n_lanes)
                    .map(|n| {
                        let mut acc = 0f32;
                        for k in 0..BF16_RANK {
                            acc += bf16_to_fp32(a[BF16_RANK * m + k])
                                * bf16_to_fp32(b[BF16_RANK * n + k]);
                        }
                        acc
                    })
                    .collect()
            })
            .collect()
    }

    /// `TOP2BF16PS` is oracle-correct: the FP32 destination equals the rank-2 BF16 outer product
    /// in the pinned order, and the operand arrays are left untouched
    /// (`[ace-tile-instructions.BF16_TOP.1]`).
    /// `top::top2bf16ps_oracle`
    #[test]
    fn top2bf16ps_oracle() {
        // Mix of integers and a fraction, all BF16-exact. A carries a 1.5 so a decode-as-integer
        // bug would explode; B is asymmetric so a transposed model would diverge.
        let mut af = [0f32; 32];
        let mut bf = [0f32; 32];
        af[0..2].copy_from_slice(&[1.5, 2.0]); // A row 0
        af[2..4].copy_from_slice(&[3.0, 4.0]); // A row 1
        bf[0..2].copy_from_slice(&[2.0, 1.0]); // B row 0
        bf[2..4].copy_from_slice(&[0.0, 3.0]); // B row 1
        let a = to_bf16(&af);
        let b = to_bf16(&bf);

        let mut scope = fp32_scope(2, 2);
        let dst = scope.tile(0).unwrap();
        _tile_top2bf16ps(&mut scope, dst, a, b);

        assert_eq!(
            read_matrix_f32(&scope, dst),
            reference_bf16(2, 2, &a, &b),
            "TOP2BF16PS == rank-2 BF16 outer product"
        );
        // Sources are taken by value; the caller's arrays are unchanged by construction, and a
        // second run into a fresh tile reproduces the same result.
        assert_eq!(
            bf16_product(2, 2, a, b),
            reference_bf16(2, 2, &a, &b),
            "operand arrays untouched across runs"
        );
    }

    /// Outer-product bilinearity (`[ace-tile-instructions.TESTING.3]`): on a zeroed tile the BF16
    /// product is linear in each operand. All operand values (and their sums and products) are
    /// small integers, hence BF16-exact and FP32-exact, so the equalities are bit-for-bit.
    /// `top::bf16_outer_product_bilinearity`
    #[test]
    fn bf16_outer_product_bilinearity() {
        let a1f: [f32; 32] = core::array::from_fn(|i| (i % 3) as f32);
        let a2f: [f32; 32] = core::array::from_fn(|i| (i % 2) as f32);
        let b1f: [f32; 32] = core::array::from_fn(|i| (i % 4) as f32);
        let b2f: [f32; 32] = core::array::from_fn(|i| (i % 2) as f32);
        let asumf: [f32; 32] = core::array::from_fn(|i| a1f[i] + a2f[i]);
        let bsumf: [f32; 32] = core::array::from_fn(|i| b1f[i] + b2f[i]);

        let (a1, a2, b1, b2) = (to_bf16(&a1f), to_bf16(&a2f), to_bf16(&b1f), to_bf16(&b2f));
        let (asum, bsum) = (to_bf16(&asumf), to_bf16(&bsumf));

        let add = |x: &[Vec<f32>], y: &[Vec<f32>]| -> Vec<Vec<f32>> {
            x.iter()
                .zip(y)
                .map(|(rx, ry)| rx.iter().zip(ry).map(|(&a, &b)| a + b).collect())
                .collect()
        };

        // Additive in a.
        let lhs_a = bf16_product(4, 4, asum, b1);
        let rhs_a = add(&bf16_product(4, 4, a1, b1), &bf16_product(4, 4, a2, b1));
        assert_eq!(lhs_a, rhs_a, "P(a1+a2, b) == P(a1,b) + P(a2,b)");

        // Additive in b.
        let lhs_b = bf16_product(4, 4, a1, bsum);
        let rhs_b = add(&bf16_product(4, 4, a1, b1), &bf16_product(4, 4, a1, b2));
        assert_eq!(lhs_b, rhs_b, "P(a, b1+b2) == P(a,b1) + P(a,b2)");
    }

    /// TILEZERO-then-accumulate equals a plain product (INV-4,
    /// `[ace-tile-instructions.TESTING.3]`): on a zeroed tile a single `TOP2BF16PS` writes exactly
    /// the outer product `P`; accumulating again writes `2P`; and `TILEZERO` then one product
    /// writes `P` again. All values are small integers so the FP32 folds are exact.
    /// `top::bf16_tilezero_then_accumulate_plain_product`
    #[test]
    fn bf16_tilezero_then_accumulate_plain_product() {
        let af: [f32; 32] = core::array::from_fn(|i| (i % 5) as f32 - 2.0);
        let bf: [f32; 32] = core::array::from_fn(|i| (i % 4) as f32 - 1.0);
        let a = to_bf16(&af);
        let b = to_bf16(&bf);
        let p = reference_bf16(3, 3, &a, &b);
        let twice: Vec<Vec<f32>> = p
            .iter()
            .map(|r| r.iter().map(|&v| v + v).collect())
            .collect();

        let mut scope = fp32_scope(3, 3);
        let dst = scope.tile(0).unwrap();

        _tile_top2bf16ps(&mut scope, dst, a, b);
        assert_eq!(read_matrix_f32(&scope, dst), p, "zeroed + one product == P");

        _tile_top2bf16ps(&mut scope, dst, a, b);
        assert_eq!(
            read_matrix_f32(&scope, dst),
            twice,
            "second accumulate == 2P"
        );

        _tile_zero(&mut scope, dst);
        _tile_top2bf16ps(&mut scope, dst, a, b);
        assert_eq!(
            read_matrix_f32(&scope, dst),
            p,
            "TILEZERO then one product == P"
        );
    }

    /// Hand-computed known-value pins (`[ace-tile-instructions.TESTING.4]`), independent of the
    /// implementation. These DISCRIMINATE the implemented model from three wrong alternatives:
    /// (1) a rank-2 widened OUTER product vs a naive full-array sum; (2) correct BF16 DECODE
    /// (`bf16_to_fp32`) vs treating the `u16` bits as an integer or truncating; (3) the
    /// `C[m][n] = A-row m · B-row n` orientation vs a transposed model (the pin matrix is
    /// asymmetric).
    /// `top::bf16_known_value_pins`
    #[test]
    fn bf16_known_value_pins() {
        // 2x2 tile, RANK=2. A rows: [1.5, 2.0] and [3.0, 4.0]; B rows: [2.0, 1.0] and [0.0, 3.0].
        //   C[0][0] = 1.5*2.0 + 2.0*1.0 = 5.0
        //   C[0][1] = 1.5*0.0 + 2.0*3.0 = 6.0
        //   C[1][0] = 3.0*2.0 + 4.0*1.0 = 10.0
        //   C[1][1] = 3.0*0.0 + 4.0*3.0 = 12.0
        // Asymmetric matrix (C[0][1] != C[1][0]) discriminates the transposed model; the 1.5
        // element only produces 5.0 under a real BF16 decode (0x3FC0 as a raw integer is 16320,
        // which would blow the result up); a naive full-array sum would collapse to one scalar.
        let mut af = [0f32; 32];
        let mut bf = [0f32; 32];
        af[0..2].copy_from_slice(&[1.5, 2.0]);
        af[2..4].copy_from_slice(&[3.0, 4.0]);
        bf[0..2].copy_from_slice(&[2.0, 1.0]);
        bf[2..4].copy_from_slice(&[0.0, 3.0]);

        let got = bf16_product(2, 2, to_bf16(&af), to_bf16(&bf));
        assert_eq!(
            got,
            vec![vec![5.0, 6.0], vec![10.0, 12.0]],
            "rank-2 BF16 outer product pins (asymmetric, decode-sensitive)"
        );

        // Decode pin: a lone BF16 1.0 (0x3F80) times a lone 3.0 (0x4040) must give 3.0, not the
        // product of the raw integers (which would be enormous).
        let mut ea = [0u16; 32];
        let mut eb = [0u16; 32];
        ea[0] = 0x3F80; // BF16 1.0
        eb[0] = 0x4040; // BF16 3.0
        assert_eq!(
            bf16_product(1, 1, ea, eb)[0][0],
            3.0,
            "BF16 1.0 * 3.0 decodes to 3.0 (not raw-integer product)"
        );
    }

    /// System-as-a-whole wiring check for family F: the full BF16 rank-2 accumulate end to end,
    /// printing observable FP32-tile state — a `TOP2BF16PS` accumulate mutates `dst` as
    /// `C_prev + rank-2 product`, and `TILEZERO` then one product equals the plain product.
    #[test]
    fn bf16_end_to_end_top2_accumulate() {
        let af: [f32; 32] = core::array::from_fn(|i| (i % 5) as f32 - 2.0);
        let bf: [f32; 32] = core::array::from_fn(|i| (i % 4) as f32 - 1.0);
        let a = to_bf16(&af);
        let b = to_bf16(&bf);
        let product = reference_bf16(2, 2, &a, &b);

        let mut scope = fp32_scope(2, 2);
        let dst = scope.tile(0).unwrap();

        _tile_top2bf16ps(&mut scope, dst, a, b);
        let c_prev = read_matrix_f32(&scope, dst);
        println!("E2E bf16 c_prev = {c_prev:?}");

        _tile_top2bf16ps(&mut scope, dst, a, b);
        let c_after = read_matrix_f32(&scope, dst);
        println!("E2E bf16 c_after (C_prev + product) = {c_after:?}");
        let expected: Vec<Vec<f32>> = c_prev
            .iter()
            .zip(&product)
            .map(|(pr, pp)| pr.iter().zip(pp).map(|(&x, &y)| x + y).collect())
            .collect();
        assert_eq!(
            c_after, expected,
            "accumulate mutates dst as C_prev + rank-2 BF16 product"
        );

        _tile_zero(&mut scope, dst);
        _tile_top2bf16ps(&mut scope, dst, a, b);
        let c_zeroed = read_matrix_f32(&scope, dst);
        println!("E2E bf16 tilezero-then-one-product = {c_zeroed:?}; plain product = {product:?}");
        assert_eq!(
            c_zeroed, product,
            "TILEZERO then one product == plain product"
        );
    }

    // -----------------------------------------------------------------------------------------
    // Family E — MX-FP8 rank-4 outer products with a per-block BSR scale (phase 7) tests.
    // -----------------------------------------------------------------------------------------

    use crate::bsr::{_tile_bsrinit, _tile_bsrmovf, BSR_SCALE_BLOCKS};

    /// Independent MX reference: the rank-4 outer product over the shared decoders and the same
    /// per-block E8M0 scale model, folded left-to-right (the reference and oracle share the
    /// decode + scale primitives but not the accumulation code, exactly as the BF16 reference
    /// does). `scales` are the E8M0 exponents; the scale is applied to each decoded operand
    /// before the multiply (pinned order).
    fn reference_mx<T: Copy>(
        m_rows: usize,
        n_lanes: usize,
        a: &[T; 64],
        b: &[T; 64],
        scales: &[u8; BSR_SCALE_BLOCKS],
        da: impl Fn(T) -> f32,
        db: impl Fn(T) -> f32,
    ) -> Vec<Vec<f32>> {
        (0..m_rows)
            .map(|m| {
                (0..n_lanes)
                    .map(|n| {
                        let mut acc = 0f32;
                        for k in 0..MX_RANK {
                            let s = mx_block_scale(scales[k]);
                            acc += (da(a[MX_RANK * m + k]) * s) * (db(b[MX_RANK * n + k]) * s);
                        }
                        acc
                    })
                    .collect()
            })
            .collect()
    }

    /// bf8/hf8 byte for a small non-negative integer (0..=4), used by the bilinearity property
    /// where the operand sums must stay exactly representable. (0x3C = 1.0 as BF8; 0x40 = 2.0.)
    fn bf8_small(v: u8) -> u8 {
        match v {
            0 => 0x00,
            1 => 0x3C,
            2 => 0x40,
            3 => 0x42,
            4 => 0x44,
            _ => unreachable!("bf8_small covers 0..=4"),
        }
    }

    /// Run one FP8-variant dispatcher once on a freshly zeroed `m×n` FP32 tile whose BSR register
    /// 0 is seeded with `exps`, returning the result matrix (the plain block-scaled product).
    fn run_fp8_variant(
        op: fn(&mut TileScope, TileId, [u8; 64], [u8; 64], BsrId),
        m_rows: u8,
        n_lanes: u16,
        a: [u8; 64],
        b: [u8; 64],
        exps: [u8; BSR_SCALE_BLOCKS],
    ) -> Vec<Vec<f32>> {
        let mut scope = fp32_scope(m_rows, n_lanes);
        let bsr = scope.bsr(0).unwrap();
        _tile_bsrinit(&mut scope, bsr, exps);
        let dst = scope.tile(0).unwrap();
        op(&mut scope, dst, a, b, bsr);
        read_matrix_f32(&scope, dst)
    }

    /// As [`run_fp8_variant`] but for the signed×signed `TOP4MXBSSPS` form (`[i8;64]` operands).
    fn run_bssps(
        m_rows: u8,
        n_lanes: u16,
        a: [i8; 64],
        b: [i8; 64],
        exps: [u8; BSR_SCALE_BLOCKS],
    ) -> Vec<Vec<f32>> {
        let mut scope = fp32_scope(m_rows, n_lanes);
        let bsr = scope.bsr(0).unwrap();
        _tile_bsrinit(&mut scope, bsr, exps);
        let dst = scope.tile(0).unwrap();
        _tile_top4mxbssps(&mut scope, dst, a, b, bsr);
        read_matrix_f32(&scope, dst)
    }

    /// The unit-scale exponents (E8M0 `127` = `2^0`), so a block scale of `1.0` makes the MX
    /// product equal the raw decoded outer product.
    const UNIT: [u8; BSR_SCALE_BLOCKS] = [127; BSR_SCALE_BLOCKS];

    /// The four MX mixed-format products are oracle-correct with the per-block scale applied, and
    /// they DIFFER on a format-sensitive byte — a byte that decodes differently as BF8 vs HF8 —
    /// so a swapped or wrong decoder would collapse them (`[ace-tile-instructions.MX_TOP.1..4]`).
    /// Differential tiebreaker unavailable; correctness grounded against ACE v1 §14/§12.
    /// `top::mx_fp8_bf8_hf8_variants_oracle`
    #[test]
    fn mx_fp8_bf8_hf8_variants_oracle() {
        // Bytes < 0x70 are finite under BOTH E5M2 and E4M3 (E5M2's all-ones exponent needs
        // byte & 0x7C == 0x7C; E4M3's only non-finite code is 0x7F), so every mixed-format
        // variant sees only finite decodes.
        let a: [u8; 64] = core::array::from_fn(|i| (i as u8).wrapping_mul(5) % 0x70);
        let b: [u8; 64] = core::array::from_fn(|i| (i as u8).wrapping_mul(3) % 0x70);

        // Each variant equals the reference with its matching decoder pair, on a 2x2 tile.
        assert_eq!(
            run_fp8_variant(_tile_top4mxbf8ps, 2, 2, a, b, UNIT),
            reference_mx(2, 2, &a, &b, &UNIT, fp8_e5m2_to_fp32, fp8_e5m2_to_fp32),
            "MXBF8PS == BF8×BF8 reference"
        );
        assert_eq!(
            run_fp8_variant(_tile_top4mxbhf8ps, 2, 2, a, b, UNIT),
            reference_mx(2, 2, &a, &b, &UNIT, fp8_e5m2_to_fp32, fp8_e4m3_to_fp32),
            "MXBHF8PS == BF8×HF8 reference"
        );
        assert_eq!(
            run_fp8_variant(_tile_top4mxhbf8ps, 2, 2, a, b, UNIT),
            reference_mx(2, 2, &a, &b, &UNIT, fp8_e4m3_to_fp32, fp8_e5m2_to_fp32),
            "MXHBF8PS == HF8×BF8 reference"
        );
        assert_eq!(
            run_fp8_variant(_tile_top4mxhf8ps, 2, 2, a, b, UNIT),
            reference_mx(2, 2, &a, &b, &UNIT, fp8_e4m3_to_fp32, fp8_e4m3_to_fp32),
            "MXHF8PS == HF8×HF8 reference"
        );

        // Format-sensitive discriminator on a 1x1 tile. 0x3C = 1.0 (BF8) / 1.5 (HF8);
        // 0x3A = 0.75 (BF8) / 1.25 (HF8). The four variants must give four DISTINCT values.
        let mut fa = [0u8; 64];
        let mut fb = [0u8; 64];
        fa[0] = 0x3C;
        fb[0] = 0x3A;
        let bf8 = run_fp8_variant(_tile_top4mxbf8ps, 1, 1, fa, fb, UNIT)[0][0]; // 1.0 * 0.75
        let bhf8 = run_fp8_variant(_tile_top4mxbhf8ps, 1, 1, fa, fb, UNIT)[0][0]; // 1.0 * 1.25
        let hbf8 = run_fp8_variant(_tile_top4mxhbf8ps, 1, 1, fa, fb, UNIT)[0][0]; // 1.5 * 0.75
        let hf8 = run_fp8_variant(_tile_top4mxhf8ps, 1, 1, fa, fb, UNIT)[0][0]; // 1.5 * 1.25
        assert_eq!(bf8, 0.75);
        assert_eq!(bhf8, 1.25);
        assert_eq!(hbf8, 1.125);
        assert_eq!(hf8, 1.875);
        assert!(
            bf8 != bhf8 && bf8 != hbf8 && bf8 != hf8 && bhf8 != hbf8 && bhf8 != hf8 && hbf8 != hf8,
            "the four MX formats must differ on a format-sensitive byte: bf8={bf8} bhf8={bhf8} hbf8={hbf8} hf8={hf8}"
        );
    }

    /// `TOP4MXBSSPS` is oracle-correct: block-scaled signed×signed INT8 into FP32, matching the
    /// signed reference; and the signedness is load-bearing — a byte with its high bit set
    /// contributes a NEGATIVE term (an unsigned widening would flip its sign)
    /// (`[ace-tile-instructions.MX_TOP.5]`). Grounded against ACE v1 §14/§12.
    /// `top::mx_bssps_signed_signed_oracle`
    #[test]
    fn mx_bssps_signed_signed_oracle() {
        let a: [i8; 64] = core::array::from_fn(|i| (i as i8).wrapping_mul(3).wrapping_sub(20));
        let b: [i8; 64] = core::array::from_fn(|i| (i as i8).wrapping_mul(5).wrapping_sub(30));
        assert_eq!(
            run_bssps(2, 2, a, b, UNIT),
            reference_mx(2, 2, &a, &b, &UNIT, |x| x as f32, |x| x as f32),
            "MXBSSPS == signed×signed reference"
        );

        // Signed discriminator: a[0]=3, b[0]=-2 (1x1) => 3 * -2 = -6.0. An unsigned widening of
        // b[0]=-2 (0xFE = 254) would give 3 * 254 = 762 — a different sign and magnitude.
        let mut sa = [0i8; 64];
        let mut sb = [0i8; 64];
        sa[0] = 3;
        sb[0] = -2;
        assert_eq!(
            run_bssps(1, 1, sa, sb, UNIT)[0][0],
            -6.0,
            "MXBSSPS widens signed: 3 * -2 = -6 (not 3 * 254)"
        );
    }

    /// BSR write/read consistency through the PRODUCT path (INV-5,
    /// `[ace-tile-instructions.BSR.4-1]`): the scale the MX product applies is exactly the scale
    /// the family-D `BSR*` ops wrote into the addressed register. Seed a non-unit scale, run the
    /// product, and confirm it equals the reference using the scale READ BACK from the guard —
    /// and that it does NOT equal the reference computed with a unit (default) scale, proving the
    /// product actually consumed the written scale. Grounded against ACE v1 §14/§12.
    /// `top::mx_bsr_write_read_consistency`
    #[test]
    fn mx_bsr_write_read_consistency() {
        // s0 = 2^(128-127) = 2 on block 0; unit elsewhere.
        let exps: [u8; BSR_SCALE_BLOCKS] = [128, 127, 127, 127];
        let mut a = [0u8; 64];
        let mut b = [0u8; 64];
        // Nonzero at k=0 on both operand rows so block-0's scale is load-bearing.
        a[0] = 0x3C; // BF8 1.0
        a[4] = 0x3C;
        b[0] = 0x3C;
        b[4] = 0x3C;

        let mut scope = fp32_scope(2, 2);
        let bsr = scope.bsr(0).unwrap();
        _tile_bsrinit(&mut scope, bsr, exps);
        // The scale reads back through the shared model exactly as written (INV-5).
        assert_eq!(scope.bsr_reg(bsr).scales(), &exps);

        let dst = scope.tile(0).unwrap();
        _tile_top4mxbf8ps(&mut scope, dst, a, b, bsr);
        let got = read_matrix_f32(&scope, dst);

        // Equals the reference using the scale READ BACK from the guard.
        let readback = *scope.bsr_reg(bsr).scales();
        assert_eq!(
            got,
            reference_mx(2, 2, &a, &b, &readback, fp8_e5m2_to_fp32, fp8_e5m2_to_fp32),
            "product applies the written block scale"
        );
        // Discriminating: it does NOT match a unit-scale reference (so the scale was truly used).
        assert_ne!(
            got,
            reference_mx(2, 2, &a, &b, &UNIT, fp8_e5m2_to_fp32, fp8_e5m2_to_fp32),
            "a non-unit written scale must change the product vs unit scale"
        );
        // Concretely: C[0][0] = s0^2 * 1.0 * 1.0 = 4.0 (unit scale would give 1.0).
        assert_eq!(got[0][0], 4.0);
    }

    /// Outer-product bilinearity (`[ace-tile-instructions.TESTING.3]`): on a zeroed tile with a
    /// unit block scale the MX (BF8) product is linear in each operand. All operand values (and
    /// their elementwise sums) are small integers, hence BF8-exact and FP32-exact, so the
    /// equalities are bit-for-bit.
    /// `top::mx_outer_product_bilinearity`
    #[test]
    fn mx_outer_product_bilinearity() {
        // Elements in {0,1}; sums land in {0,1,2} — all BF8-exact.
        let a1: [u8; 64] = core::array::from_fn(|i| bf8_small((i % 2) as u8));
        let a2: [u8; 64] = core::array::from_fn(|i| bf8_small(((i / 2) % 2) as u8));
        let b1: [u8; 64] = core::array::from_fn(|i| bf8_small((i % 2) as u8));
        let b2: [u8; 64] = core::array::from_fn(|i| bf8_small(((i / 3) % 2) as u8));
        // Decoded-domain sums, re-encoded (each sum is 0/1/2, all BF8-exact).
        let dec = fp8_e5m2_to_fp32;
        let asum: [u8; 64] = core::array::from_fn(|i| bf8_small((dec(a1[i]) + dec(a2[i])) as u8));
        let bsum: [u8; 64] = core::array::from_fn(|i| bf8_small((dec(b1[i]) + dec(b2[i])) as u8));

        let prod = |a, b| run_fp8_variant(_tile_top4mxbf8ps, 4, 4, a, b, UNIT);
        let add = |x: &[Vec<f32>], y: &[Vec<f32>]| -> Vec<Vec<f32>> {
            x.iter()
                .zip(y)
                .map(|(rx, ry)| rx.iter().zip(ry).map(|(&a, &b)| a + b).collect())
                .collect()
        };

        assert_eq!(
            prod(asum, b1),
            add(&prod(a1, b1), &prod(a2, b1)),
            "P(a1+a2, b) == P(a1,b) + P(a2,b)"
        );
        assert_eq!(
            prod(a1, bsum),
            add(&prod(a1, b1), &prod(a1, b2)),
            "P(a, b1+b2) == P(a,b1) + P(a,b2)"
        );
    }

    /// Hand-computed known-value pins (`[ace-tile-instructions.TESTING.4]`), independent of the
    /// implementation, that DISCRIMINATE the model from wrong alternatives: (1) each of the four
    /// mixed formats decodes with the right BF8/HF8 codec; (2) a scaled product differs from an
    /// unscaled one; (3) the scale is applied BEFORE the multiply per block, not to the
    /// accumulated sum afterwards; (4) `MXBSSPS` widens signed. Grounded against ACE v1 §14/§12.
    /// `top::mx_known_value_pins`
    #[test]
    fn mx_known_value_pins() {
        // (1) Format pins on a 1x1 tile, unit scale, a[0]=0x3C (BF8 1.0 / HF8 1.5),
        //     b[0]=0x3A (BF8 0.75 / HF8 1.25).
        let mut fa = [0u8; 64];
        let mut fb = [0u8; 64];
        fa[0] = 0x3C;
        fb[0] = 0x3A;
        assert_eq!(
            run_fp8_variant(_tile_top4mxbf8ps, 1, 1, fa, fb, UNIT)[0][0],
            0.75
        );
        assert_eq!(
            run_fp8_variant(_tile_top4mxbhf8ps, 1, 1, fa, fb, UNIT)[0][0],
            1.25
        );
        assert_eq!(
            run_fp8_variant(_tile_top4mxhbf8ps, 1, 1, fa, fb, UNIT)[0][0],
            1.125
        );
        assert_eq!(
            run_fp8_variant(_tile_top4mxhf8ps, 1, 1, fa, fb, UNIT)[0][0],
            1.875
        );

        // (2) Scaled vs unscaled. a[0]=b[0]=BF8 1.0. Unit scale => 1.0; block-0 exp 128
        //     (s0 = 2) => s0^2 * 1.0 * 1.0 = 4.0. Scaled MUST differ from unscaled.
        let mut ua = [0u8; 64];
        let mut ub = [0u8; 64];
        ua[0] = 0x3C;
        ub[0] = 0x3C;
        let unscaled = run_fp8_variant(_tile_top4mxbf8ps, 1, 1, ua, ub, UNIT)[0][0];
        let scaled = run_fp8_variant(_tile_top4mxbf8ps, 1, 1, ua, ub, [128, 127, 127, 127])[0][0];
        assert_eq!(unscaled, 1.0, "unit scale: 1.0 * 1.0 = 1.0");
        assert_eq!(scaled, 4.0, "block-0 s0=2: s0^2 * 1.0 * 1.0 = 4.0");
        assert_ne!(
            scaled, unscaled,
            "a scaled product differs from an unscaled one"
        );

        // (3) Scale-applied-BEFORE-multiply-per-block vs after accumulation. Contraction depth
        //     2: a=[1.0,1.0,..], b=[1.0,1.0,..] (BF8), exps=[128,127,..] so s0=2, s1=1.
        //     Before-multiply per block: s0^2*1*1 + s1^2*1*1 = 4 + 1 = 5.0.
        //     Scaling the accumulated dot (1*1 + 1*1 = 2) by s0 afterwards would give 4.0 — a
        //     different value, so this pins the application order.
        let mut pa = [0u8; 64];
        let mut pb = [0u8; 64];
        pa[0] = 0x3C;
        pa[1] = 0x3C;
        pb[0] = 0x3C;
        pb[1] = 0x3C;
        let before = run_fp8_variant(_tile_top4mxbf8ps, 1, 1, pa, pb, [128, 127, 127, 127])[0][0];
        assert_eq!(
            before, 5.0,
            "scale before multiply per block: 4 + 1 = 5 (scaling the sum afterwards would give 4)"
        );

        // (4) MXBSSPS widens signed: a[0]=3, b[0]=-2, unit scale => -6.0.
        let mut sa = [0i8; 64];
        let mut sb = [0i8; 64];
        sa[0] = 3;
        sb[0] = -2;
        assert_eq!(run_bssps(1, 1, sa, sb, UNIT)[0][0], -6.0);
    }

    /// System-as-a-whole wiring check for family E: seed a BSR scale with the phase-4 `BSR*` ops
    /// (`BSRINIT` + `BSRMOVF`), run an MX-FP8 product that reads that same scale back (INV-5), and
    /// confirm it accumulates `C_prev + block-scaled rank-4 product` into the FP32 tile. Prints
    /// the observable BSR readback and tile state and the gate helper family E reads.
    #[test]
    fn mx_end_to_end_top4_accumulate() {
        // Write the block scale via the phase-4 ops: unit everywhere, then MOVF block 0 to 128
        // (s0 = 2). This is the exact scale the product must read back (INV-5).
        let mut scope = fp32_scope(2, 2);
        let bsr = scope.bsr(0).unwrap();
        _tile_bsrinit(&mut scope, bsr, UNIT);
        _tile_bsrmovf(&mut scope, bsr, 0, 128).unwrap();
        let readback = *scope.bsr_reg(bsr).scales();
        println!("E2E mx bsr readback = {readback:?}");
        assert_eq!(
            readback,
            [128, 127, 127, 127],
            "BSR* wrote the scale the product reads"
        );

        // BF8 operands: a rows [1.0,1.0,..], b rows [1.0,1.0,..].
        let mut a = [0u8; 64];
        let mut b = [0u8; 64];
        for m in 0..2 {
            a[MX_RANK * m] = 0x3C;
            a[MX_RANK * m + 1] = 0x3C;
            b[MX_RANK * m] = 0x3C;
            b[MX_RANK * m + 1] = 0x3C;
        }
        // Independent product P from the reference, using the SCALE READ BACK from the guard.
        let product = reference_mx(2, 2, &a, &b, &readback, fp8_e5m2_to_fp32, fp8_e5m2_to_fp32);

        let dst = scope.tile(0).unwrap();
        _tile_top4mxbf8ps(&mut scope, dst, a, b, bsr);
        let c_prev = read_matrix_f32(&scope, dst);
        println!("E2E mx c_prev = {c_prev:?}");
        assert_eq!(c_prev, product, "zeroed + one product == block-scaled P");

        _tile_top4mxbf8ps(&mut scope, dst, a, b, bsr);
        let c_after = read_matrix_f32(&scope, dst);
        println!("E2E mx c_after (C_prev + product) = {c_after:?}");
        let expected: Vec<Vec<f32>> = c_prev
            .iter()
            .zip(&product)
            .map(|(pr, pp)| pr.iter().zip(pp).map(|(&x, &y)| x + y).collect())
            .collect();
        assert_eq!(
            c_after, expected,
            "accumulate mutates dst as C_prev + block-scaled rank-4 product"
        );
        println!("E2E detect has_ace={}", crate::detect::has_ace());
    }
}

/// Layer-4 differential (families E/F/G). Bit-for-bit native-vs-oracle agreement of the `TOP*`
/// outer products: under `feature="native"` on x86_64 with full `ACE` detected, the native
/// `.byte` path must equal the scalar oracle bit-for-bit (`[ace-tile-instructions.TESTING.1]`).
/// These families are `ACE`-only and their `.byte` native arm is layer-3-blocked until Intel SDE
/// gains ACE emulation (OQ-6, R2), so this returns [`quickcheck::TestResult::discard`] — never
/// `from_bool(false)` — on every current host, discarding until SDE ACE lands rather than
/// passing vacuously or failing. `TOP4BSSD` is the representative INT8 form; the BF16 (F) and
/// MX-FP8 (E) forms share the identical posture and native shims (`crate::native::top*_hw`).
#[cfg(test)]
mod differential {
    #![cfg_attr(
        not(all(target_arch = "x86_64", feature = "native")),
        allow(unused_imports, dead_code)
    )]
    use super::*;
    use crate::bsr::_tile_bsrinit;
    use crate::tile::{_tile_loadconfig, TileConfig, TileId, TileScope};
    use quickcheck::{quickcheck, Arbitrary, Gen, TestResult};

    /// Random operands for a single-row (`1 x 16`) `TOP*` accumulate, plus a prior accumulator
    /// and the per-block BSR exponents the MX (family E) forms read.
    #[derive(Clone, Debug)]
    struct Inputs {
        c_prev: [i32; MAX_ACC_LANES],
        a: [i8; 64],
        b: [i8; 64],
        bexp: [u8; crate::bsr::BSR_SCALE_BLOCKS],
    }

    impl Arbitrary for Inputs {
        fn arbitrary(g: &mut Gen) -> Self {
            Inputs {
                c_prev: core::array::from_fn(|_| i32::arbitrary(g)),
                a: core::array::from_fn(|_| i8::arbitrary(g)),
                b: core::array::from_fn(|_| i8::arbitrary(g)),
                bexp: core::array::from_fn(|_| u8::arbitrary(g)),
            }
        }
    }

    #[cfg(all(target_arch = "x86_64", feature = "native"))]
    const CFG_1X16: TileConfig = TileConfig {
        palette_id: 2,
        rows: [1, 0, 0, 0, 0, 0, 0, 0],
        colsb: [64, 0, 0, 0, 0, 0, 0, 0],
    };

    /// A fresh 1x16 accumulator tile seeded with the prior `C`.
    #[cfg(all(target_arch = "x86_64", feature = "native"))]
    fn fresh(c_prev: &[i32; MAX_ACC_LANES]) -> (TileScope, TileId) {
        let mut scope = _tile_loadconfig(&CFG_1X16).expect("valid descriptor");
        let dst = scope.tile(0).unwrap();
        let bytes = scope.tile_bytes_mut(dst);
        for (n, &c) in c_prev.iter().enumerate() {
            bytes[n * 4..n * 4 + 4].copy_from_slice(&c.to_le_bytes());
        }
        (scope, dst)
    }

    quickcheck! {
        /// Full family G/F/E native-vs-oracle differential over a 1x16 tile. Discards on every
        /// non-ACE host (OQ-6); lights up bit-for-bit under an ACE-capable SDE.
        fn prop_native_matches_oracle(input: Inputs) -> TestResult {
            #[cfg(all(target_arch = "x86_64", feature = "native"))]
            {
                if detect::has_ace() {
                    use crate::native::{self, TILE_BYTES};
                    let cfg = native::encode_tilecfg(2, &CFG_1X16.rows, &CFG_1X16.colsb);
                    let mut c_in = [0u8; TILE_BYTES];
                    for (n, &c) in input.c_prev.iter().enumerate() {
                        c_in[n * 4..n * 4 + 4].copy_from_slice(&c.to_le_bytes());
                    }
                    let a_u: [u8; 64] = core::array::from_fn(|i| input.a[i] as u8);
                    let b_u: [u8; 64] = core::array::from_fn(|i| input.b[i] as u8);
                    let a_bytes: [u8; TILE_BYTES] = a_u;
                    let b_bytes: [u8; TILE_BYTES] = b_u;

                    // Family G — all four INT8 signedness forms.
                    let mut ok = true;
                    macro_rules! check_int8 {
                        ($oracle:ident, $hw:ident, $a:expr, $b:expr) => {{
                            let (mut s, d) = fresh(&input.c_prev);
                            $oracle(&mut s, d, $a, $b);
                            let want = s.tile_bytes_ref(d).to_vec();
                            // SAFETY: has_ace() confirmed full ACE + tile/BSR XSAVE state.
                            let got = unsafe { native::$hw(&cfg, &c_in, &a_bytes, &b_bytes) };
                            ok &= got.as_slice() == want.as_slice();
                        }};
                    }
                    check_int8!(_tile_top4bssd_scalar, top4bssd_hw, input.a, input.b);
                    check_int8!(_tile_top4bsud_scalar, top4bsud_hw, input.a, b_u);
                    check_int8!(_tile_top4busd_scalar, top4busd_hw, a_u, input.b);
                    check_int8!(_tile_top4buud_scalar, top4buud_hw, a_u, b_u);

                    // Family F — BF16 rank-2 (operands are the same 64 bytes as 32 u16 lanes).
                    {
                        let a16: [u16; 32] = core::array::from_fn(|i| {
                            u16::from_le_bytes([a_u[2 * i], a_u[2 * i + 1]])
                        });
                        let b16: [u16; 32] = core::array::from_fn(|i| {
                            u16::from_le_bytes([b_u[2 * i], b_u[2 * i + 1]])
                        });
                        let (mut s, d) = fresh(&input.c_prev);
                        _tile_top2bf16ps_scalar(&mut s, d, a16, b16);
                        let want = s.tile_bytes_ref(d).to_vec();
                        let got = unsafe { native::top2bf16ps_hw(&cfg, &c_in, &a_bytes, &b_bytes) };
                        ok &= got.as_slice() == want.as_slice();
                    }

                    // Family E — MX-FP8 forms with the per-block BSR scale.
                    let mut bsr_buf = [0u8; TILE_BYTES];
                    bsr_buf[..crate::bsr::BSR_SCALE_BLOCKS].copy_from_slice(&input.bexp);
                    macro_rules! check_mx {
                        ($oracle:ident, $hw:ident, $a:expr, $b:expr) => {{
                            let (mut s, d) = fresh(&input.c_prev);
                            let bid = s.bsr(0).unwrap();
                            _tile_bsrinit(&mut s, bid, input.bexp);
                            $oracle(&mut s, d, $a, $b, bid);
                            let want = s.tile_bytes_ref(d).to_vec();
                            let got =
                                unsafe { native::$hw(&cfg, &c_in, &a_bytes, &b_bytes, &bsr_buf) };
                            ok &= got.as_slice() == want.as_slice();
                        }};
                    }
                    check_mx!(_tile_top4mxbf8ps_scalar, top4mxbf8ps_hw, a_u, b_u);
                    check_mx!(_tile_top4mxbhf8ps_scalar, top4mxbhf8ps_hw, a_u, b_u);
                    check_mx!(_tile_top4mxhbf8ps_scalar, top4mxhbf8ps_hw, a_u, b_u);
                    check_mx!(_tile_top4mxhf8ps_scalar, top4mxhf8ps_hw, a_u, b_u);
                    check_mx!(_tile_top4mxbssps_scalar, top4mxbssps_hw, input.a, input.b);

                    return TestResult::from_bool(ok);
                }
            }
            let _ = &input;
            TestResult::discard()
        }
    }
}
